---
trigger: none
name: Setup ${parameters.environment} App Infra
appendCommitMessageToRunName: false 

parameters:
  - name: environment
    displayName: Select Environment
    type: string
    default: Development
    values:
      - Development
      - Stage 
      - Production 



