---
trigger: none
name: Setup ${parameters.environment} App Infra
appendCommitMessageToRunName: false 

parameters:
  - name: environment
    displayName: Select Environment
    type: string
    default: Development
    values:
      - Development
      - Acceptance 
      - Production 

variables:
  - name: env
    '${{ if eq(parameters.environment, ''Development'' ) }}':
      value: dev 
    '${{ if eq(parameters.environment, ''Acceptance'' ) }}':
      value: acc
    '${{ if eq(parameters.environment, ''Production'' ) }}':
      value: prd