--- 
trigger: none
appendCommitMessageToRunName: false

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: environment
    displayName: Select Environment
    default: Development
    values:
      - Development
      - Staging
      - Production
  
  - name: package
    displayName: Select Package
    type: string
    default: All
    values:
      - All
      - NodeJS 
      - PM2 
      - SQL-Client
  
  - name: upgrade 
    displayName: Upgrade Package
    type: boolean
    default: false

variables:
  - name: ansibleUser
    '${{ if eq(parameters.environment, ''Production'') }}':
      value: ansible-prd
    ${{ else }}:
      value: ansible-nonprd
  
  - name: ansibleTags 
    '${{ if eq(parameters.package, ''NodeJS'') }}':
      value: nodejs
    '${{ if eq(parameters.package,  ''PM2'') }}':
      value: pm2
    '${{ if eq(parameters.package, ''SQL-Client'') }}':
      value: sql-client
    '${{ else }}':
      value: '*'

jobs:
  - job: app_infra_setup
    displayName: Webapp ${{ parameters.environment }} Infra Setup 
    steps:
      - checkout: self 
        displayName: Checkout terraform-project-3tier-app
      
      - task: Bash@3
        displayName: Print Pipeline parameters
        inputs:
          targetType: 'inline'
          script: |
                echo "Running on agent: $(Agent.Name)"
                echo "Selected environment: ${{ parameters.environment }}"
                echo "Ansible user: $(ansibleUser)"
                echo "Ansiblbe Tags: $(ansibleTags)"
       

      - task: AzureKeyVault@2
        displayName:  Download Ansible User Secret 
        inputs:
          azureSubscription: 'azdevops-to-azcloud-federation'
          KeyVaultName: 'ansiblecreds'
          SecretsFilter: '$(ansibleUser)'
          RunAsPreJob: true
      
      - task: Ansible@0
        displayName: Run Playbook
        env:
          ANSIBLE_CONFIG: '$(System.DefaultWorkingDirectory)/ansible/ansible.cfg'
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible/configure-webapp-infra.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/ansible/inventory/Development.ini'
          args: '
            --extra-vars "
              ansible_user=$(ansibleUser)
              ansible_ssh_pass=$(ansibleUser)"'